import "../vendors/js/vendor.bundle.base.js"
import "../vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"
import "../vendors/chart.js/Chart.min.js"
import "../vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"
import "../vendors/progressbar.js/progressbar.min.js"
import "../js/off-canvas.js"
import "../js/hoverable-collapse.js"
import "../js/template.js"
import "../js/settings.js"
import "../js/todolist.js"
import "../js/jquery.cookie.js"
import "../js/dashboard.js"

// computer table
import "../vendors/datatables.net/jquery.dataTables.js"
import "../vendors/datatables.net-bs4/dataTables.bootstrap4.js"
import "../js/data-table.js"
